language: ruby
cache: bundler
sudo: required
services:
  - docker
before_install:
  - sudo apt-get update
  - sudo apt-cache policy docker-engine
  - 'sudo apt-get install docker-engine=1.9.1-0~trusty -yq -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold"'
  - gem install bundler
before_script:
  - docker version
  - git config --global user.email "you@example.com"
  - git config --global user.name "Your Name"
  - git config --global push.default simple
script:
  - docker build -t quay.io/assemblyline/builder:latest .
  - bundle exec rake
addons:
  code_climate:
    repo_token: 50e550bf7566d9ba05d4fc103159b9077552447a931038461f5e08e8a56b4695
